enum ApiJsonKey {
  ///region A
  ActualEndTime(key: 'ActualEndTime'),
  ActualStartTime(key: 'ActualStartTime'),
  ActualWorkTime(key: 'ActualWorkTime'),
  AdditionalPhoneNumber(key: "AdditionalPhoneNumber"),
  AdditionalSerialNumber(key: 'AdditionalSerialNumber'),
  Address(key: 'Address'),
  ///attached
  AttachedDataType(key: 'AttachedDataType'),
  AttachedMachines(key: 'AttachedMachines'),
  AttachedMachineCode(key: 'AttachedMachineCode'),
  AttachedMachineId(key: 'AttachedMachineId'),
  AttachedMachineName(key: 'AttachedMachineName'),
  AttachedMachineNumber(key: 'AttachedMachineNumber'),
  AttachedMonitoringType(key: 'AttachedMonitoringType'),
  AttachedMachineOrderIndex(key: 'AttachedMachineOrderIndex'),
  AttachedProcessType(key: 'AttachedProcessType'),
  AttachedPasDataType(key: 'AttachedPasDataType'),
  AvailablePickingQty(key: 'AvailablePickingQty'),

  ///endregion

  ///region B
  BankAccountNumber(key: "BankAccountNumber"),
  BankAccountOwnerName(key: "BankAccountOwnerName"),
  BankName(key: "BankName"),
  BasisId(key: 'BasisId'),
  BomId(key: 'BomId'),
  BomLossQuantity(key: 'BomLossQuantity'),
  Brn(key: "Brn"),
  BusinessCategory(key: "BusinessCategory"),
  BusinessType(key: "BusinessType"),
  BuyerBrn(key: 'BuyerBrn'),
  BuyerCode(key: "BuyerCode"),
  BuyerId(key: "BuyerId"),
  BuyerName(key: "BuyerName"),
  ByteOrder(key: "ByteOrder"),

  //endregion

  ///region C
  CallCodeId(key: "CallCodeId"),
  CallId(key: "CallId"),
  CallReason(key: "CallReason"),
  CallReasonCode(key: "CallReasonCode"),
  CallReasonId(key: "CallReasonId"),
  CallReasonName(key: "CallReasonName"),
  CallSeverity(key: "CallSeverity"),
  CallType(key: "CallType"),
  CanCreate(key: "CanCreate"),
  CanDelete(key: "CanDelete"),
  CanRead(key: "CanRead"),
  CanUpdate(key: "CanUpdate"),
  Caption(key: "Caption"),
  CategoryCode(key: "CategoryCode"),
  CategoryId(key: "CategoryId"),
  CategoryName(key: "CategoryName"),
  CavityNumber(key: "CavityNumber"),
  CausativeMachineCode(key: "CausativeMachineCode"),
  CausativeMachineId(key: "CausativeMachineId"),
  CausativeMachineName(key: "CausativeMachineName"),
  Cavity(key: "Cavity"),
  CavityCount(key: "CavityCount"),
  CharConversionType(key: "CharConversionType"),
  City(key: "City"),
  ClosingCompleted(key: "ClosingCompleted"),
  ClosingGrossAmount(key: "ClosingGrossAmount"),
  ClosingId(key: "ClosingId"),
  ClosingLineId(key: "ClosingLineId"),
  ClosingNetAmount(key: "ClosingNetAmount"),
  ClosingNumber(key: "ClosingNumber"),
  ClosingQuantity(key: "ClosingQuantity"),
  ClosingStatus(key: "ClosingStatus"),
  ClosingTime(key: "ClosingTime"),
  ClosingType(key: "ClosingType"),
  ClosingVatAmount(key: "ClosingVatAmount"),
  Code(key: "Code"),
  CollectionGroupDataType(key: "CollectionGroupDataType"),
  CollectionGroupDuration(key: "CollectionGroupDuration"),
  CollectionGroupId(key: "CollectionGroupId"),
  CollectionGroupName(key: "CollectionGroupName"),
  CollectionGroupPivotElement(key: "CollectionGroupPivotElement"),
  CollectionGroupSaveMethod(key: "CollectionGroupSaveMethod"),
  CollectorHostName(key: "CollectorHostName"),
  CollectorId(key: "CollectorId"),
  CollectorMachineCode(key: "CollectorMachineCode"),
  CollectorMachineId(key: "CollectorMachineId"),
  CollectorMachineName(key: "CollectorMachineName"),
  CollectorName(key: "CollectorName"),
  CollectorServerIp(key: "CollectorServerIp"),
  CollectorServerPort(key: "CollectorServerPort"),
  CollectorUseHostName(key: "CollectorUseHostName"),
  ColorCode(key: "ColorCode"),
  ColorId(key: "ColorId"),
  ColorName(key: "ColorName"),
  ColorRgb(key: "ColorRgb"),
  CompanyCode(key: "CompanyCode"),
  CompanyId(key: "CompanyId"),
  CompanyName(key: "CompanyName"),
  CompanyType(key: "CompanyType"),
  CompletionRate(key: "CompletionRate"),
  CompletionRateAverage(key: "CompletionRateAverage"),
  ConfirmType(key: "ConfirmType"),
  Count(key: "Count"),
  ContractType(key: "ContractType"),
  Country(key: "Country"),
  Crn(key: "Crn"),
  Currency(key: "Currency"),
  CurrentProcess(key: "CurrentProcess"),

  /// customer
  CustomNumber(key: 'CustomNumber'),
  CustomerOrderNumber(key: 'CustomerOrderNumber'),
  CustomSerialNumber(key: 'CustomSerialNumber'),
  CuttingMachines(key: 'CuttingMachines'),
  CycleCount(key: 'CycleCount'),
  CycleTime(key: 'CycleTime'),

  //endregion

  ///region D

  DataFields(key: "DataFields"),
  DataType(key: "DataType"),
  DateBought(key: "DateBought"),
  DateManufactured(key: "DateManufactured"),
  DateTimeCreated(key: "DateTimeCreated"),
  DecimalPoint(key: "DecimalPoint"),
  DefectLevel(key: 'DefectLevel'),
  DefectQuantity(key: 'DefectQuantity'),
  DefectRate(key: 'DefectRate'),
  DefectReason(key: 'DefectReason'),
  DefectiveRate(key: 'DefectiveRate'),
  DefectType(key: 'DefectType'),
  DeliveryDate(key: 'DeliveryDate'),
  DeliveryTypeCode(key: "DeliveryTypeCode"),
  DeliveryTypeId(key: "DeliveryTypeId"),
  DeliveryTypeName(key: "DeliveryTypeName"),
  DepartmentCode(key: "DepartmentCode"),
  DepartmentId(key: "DepartmentId"),
  DepartmentMemo(key: "DepartmentMemo"),
  DepartmentName(key: "DepartmentName"),
  Description(key: "Description"),
  DestinationCode(key: 'DestinationCode'),
  DestinationId(key: 'DestinationId'),
  DestinationName(key: 'DestinationName'),
  DeviceId(key: 'DeviceId'),
  DiePitch(key: 'DiePitch'),
  DirectionType(key: "DirectionType"),
  DiscoveryPoint(key: 'DiscoveryPoint'),
  DownRate(key: 'DownRate'),
  Downtime(key: 'Downtime'),
  DowntimeLevel(key: 'DowntimeLevel'),
  DowntimeLineCode(key: 'DowntimeLineCode'),
  DowntimeLineId(key: 'DowntimeLineId'),
  DowntimeLineName(key: 'DowntimeLineName'),
  DowntimeMachine(key: 'DowntimeMachine'),
  DowntimeMachineCode(key: 'DowntimeMachineCode'),
  DowntimeMachineId(key: 'DowntimeMachineId'),
  DowntimeMachineName(key: 'DowntimeMachineName'),
  DowntimeType(key: 'DowntimeType'),
  DueMonth(key: 'DueMonth'),
  Duration(key: 'Duration'),

  //endregion

  ///region E
  EffectiveCavity(key: 'EffectiveCavity'),
  EffectiveDate(key: "EffectiveDate"),
  EffectiveQuantity(key: 'EffectiveQuantity'),
  EffectiveReceiptQuantity(key: 'EffectiveReceiptQuantity'),
  Email(key: "Email"),
  EmployeeCode(key: 'EmployeeCode'),
  EmployeeId(key: 'EmployeeId'),
  EmployeeName(key: 'EmployeeName'),
  EnrollmentType(key: 'EnrollmentType'),
  EndTime(key: 'EndTime'),
  ExpectedCompletionRate(key: 'ExpectedCompletionRate'),

  //endregion

  ///region F
  FactoryCode(key: "FactoryCode"),
  FactoryId(key: "FactoryId"),
  FactoryName(key: "FactoryName"),
  FailCount(key: "FailCount"),
  FaxNumber(key: "FaxNumber"),
  FEnetDataType(key: "FEnetDataType"),
  FEnetMemoryType(key: "FEnetMemoryType"),
  FieldCaption(key: "FieldCaption"),
  FieldName(key: "FieldName"),
  FieldUnit(key: "FieldUnit"),
  FifoStandard(key: 'FifoStandard'),
  Frequency(key: 'Frequency'),

  //endregion

  ///region G
  Granted(key: "Granted"),
  GrossAmount(key: "GrossAmount"),
  GroupCode(key: "GroupCode"),
  GroupId(key: "GroupId"),
  GroupName(key: "GroupName"),

  //endregion

  ///region H
  Handled(key: "Handled"),
  HasMultiFactory(key: "HasMultiFactory"),
  Homepage(key: "Homepage"),
  //endregion

  ///region I
  Id(key: "Id"),
  IsCollector(key: "IsCollector"),
  InitialQty(key: "InitialQty"),
  InsertQuantity(key: "InsertQuantity"),

  ///Inspection
  InspectionConducted(key: 'InspectionConducted'),
  InsertedQuantity(key: 'InsertedQuantity'),
  InspectionCount(key: 'InspectionCount'),
  InspectionDate(key: 'InspectionDate'),
  InspectionLocation(key: 'InspectionLocation'),
  InspectionMethod(key: 'InspectionMethod'),
  InspectionResultId(key: 'InspectionResultId'),
  InspectionStatus(key: 'InspectionStatus'),
  InspectionTime(key: 'InspectionTime'),
  InspectionType(key: 'InspectionType'),
  InspectionWorkId(key: 'InspectionWorkId'),
  InspectionWorkNumber(key: 'InspectionWorkNumber'),
  IsWorkPassed(key: 'IsWorkPassed'),
  IntervalSeconds(key: 'IntervalSeconds'),
  InventoryManageType(key: 'InventoryManageType'),
  InventoryQty(key: 'InventoryQty'),
  InventoryRetentionPeriod(key: "InventoryRetentionPeriod"),
  InventorySafeQty(key: "InventorySafeQty"),
  InvoiceNumber(key: "InvoiceNumber"),
  IpAddress(key: "IpAddress"),

  ///is
  IsAdmin(key: "IsAdmin"),
  IsDiscarded(key: 'IsDiscarded'),
  IsPassed(key: 'IsPassed'),
  IsResultPassed(key: 'IsResultPassed'),
  IsSave(key: 'IsSave'),

  IsWritable(key: "IsWritable"),
  IssueCompleted(key: 'IssueCompleted'),
  IssueDueDate(key: 'IssueDueDate'),
  IssueId(key: 'IssueId'),
  IssueLineId(key: "IssueLineId"),
  IssueNumber(key: "IssueNumber"),
  IssueQuantity(key: "IssueQuantity"),
  IssueQuantityLeft(key: "IssueQuantityLeft"),
  IssueTime(key: "IssueTime"),
  IssueType(key: "IssueType"),

  ///item
  ItemCategoryCode(key: "ItemCategoryCode"),
  ItemCategoryId(key: "ItemCategoryId"),
  ItemCategoryName(key: "ItemCategoryName"),
  ItemCode(key: "ItemCode"),
  ItemColorCode(key: "ItemColorCode"),
  ItemColorId(key: "ItemColorId"),
  ItemColorName(key: "ItemColorName"),
  ItemColorRgb(key: "ItemColorRgb"),
  ItemGroupCode(key: "ItemGroupCode"),
  ItemGroupId(key: "ItemGroupId"),
  ItemGroupName(key: "ItemGroupName"),
  ItemId(key: "ItemId"),
  ItemIds(key: "ItemIds"),
  ItemMajorGroupCode(key: "ItemMajorGroupCode"),
  ItemMajorGroupId(key: "ItemMajorGroupId"),
  ItemMajorGroupName(key: "ItemMajorGroupName"),

  ///itemManufacture
  ItemManufactureCode(key: "ItemManufactureCode"),
  ItemManufactureName(key: "ItemManufactureName"),

  ///itemManufacturer
  ItemManufacturerCode(key: "ItemManufacturerCode"),
  ItemManufacturerId(key: "ItemManufacturerId"),
  ItemManufacturerName(key: "ItemManufacturerName"),
  ItemModelCode(key: "ItemModelCode"),
  ItemModelId(key: "ItemModelId"),
  ItemModelName(key: "ItemModelName"),
  ItemName(key: "ItemName"),
  ItemNumber(key: "ItemNumber"),
  ItemSpec(key: "ItemSpec"),
  ItemTextureCode(key: "ItemTextureCode"),
  ItemTextureId(key: "ItemTextureId"),
  ItemTextureName(key: "ItemTextureName"),
  ItemUnit(key: "ItemUnit"),

  //endregion

  ///region J

  //endregion

  ///region K

  //endregion

  ///region L
  LabelId(key: 'LabelId'),
  LabelNumber(key: 'LabelNumber'),
  LatestDowntimeReasonCode(key: 'LatestDowntimeReasonCode'),
  LatestDowntimeReasonId(key: 'LatestDowntimeReasonId'),
  LatestDowntimeReasonName(key: 'LatestDowntimeReasonName'),
  LatestOffDutyReasonCode(key: 'LatestOffDutyReasonCode'),
  LatestOffDutyReasonId(key: 'LatestOffDutyReasonId'),
  LatestOffDutyReasonName(key: 'LatestOffDutyReasonName'),
  LatestOffDutyTime(key: 'LatestOffDutyTime'),
  LatestReworkReasonCode(key: 'LatestReworkReasonCode'),
  LatestReworkReasonId(key: 'LatestReworkReasonId'),
  LatestReworkReasonName(key: 'LatestReworkReasonName'),
  LatestReworkTime(key: 'LatestReworkTime'),
  LB(key: 'LB'),
  Length(key: 'Length'),
  LineCode(key: "LineCode"),
  LineId(key: "LineId"),
  LineItems(key: "LineItems"),
  LineName(key: "LineName"),
  LineNumber(key: "LineNumber"),
  LoadingQuantity(key: "LoadingQuantity"),
  LocationCode(key: "LocationCode"),
  LocationGroupCode(key: 'LocationGroupCode'),
  LocationGroupId(key: 'LocationGroupId'),
  LocationGroupName(key: 'LocationGroupName'),
  LocationId(key: "LocationId"),
  LocationName(key: "LocationName"),
  LoginId(key: "LoginId"),
  LoginPassword(key: "LoginPassword"),
  LoginTag(key: "LoginTag"),
  LossRate(key: 'LossRate'),
  LotCreationDate(key: 'LotCreationDate'),
  LotId(key: 'LotId'),
  LotIds(key: 'LotIds'),
  LotNumber(key: 'LotNumber'),
  LotNumbers(key: 'LotNumbers'),
  LotType(key: 'LotType'),

  //endregion

  ///region M

  ///machine
  MachineCode(key: "MachineCode"),
  MachineId(key: "MachineId"),
  MachineName(key: "MachineName"),
  MachineNumber(key: "MachineNumber"),
  MachineOrderIndex(key: "MachineOrderIndex"),
  ///main
  MainDataType(key: "MainDataType"),
  MainMachineCode(key: "MainMachineCode"),
  MainMachineId(key: "MainMachineId"),
  MainMachineName(key: "MainMachineName"),
  MainMachineNumber(key: "MainMachineNumber"),
  MainMachineOrderIndex(key: "MainMachineOrderIndex"),
  MainMonitoringType(key: "MainMonitoringType"),
  MainPasDataType(key: "MainPasDataType"),
  MainProcessType(key: "MainProcessType"),
  MajorGroupCode(key: "MajorGroupCode"),
  MajorGroupId(key: "MajorGroupId"),
  MajorGroupName(key: "MajorGroupName"),
  Maker(key: "Maker"),
  ManagerCode(key: "ManagerCode"),
  ManagerId(key: "ManagerId"),
  ManagerIds(key: "ManagerIds"),
  ManagerName(key: "ManagerName"),
  ManufactureDate(key: 'ManufactureDate'),
  ManufactureNumber(key: 'ManufactureNumber'),
  ManualInsertQuantity(key: 'ManualInsertQuantity'),
  MaterialCode(key: 'MaterialCode'),
  MaterialId(key: 'MaterialId'),
  MaterialName(key: 'MaterialName'),
  MaterialNumber(key: 'MaterialNumber'),
  MaterialUnit(key: 'MaterialUnit'),
  Materials(key: 'Materials'),
  Memo(key: "Memo"),
  Message(key: "Message"),
  Menu(key: "Menu"),
  ManufacturerCode(key: "ManufacturerCode"),
  ManufacturerId(key: "ManufacturerId"),
  ManufacturerName(key: "ManufacturerName"),
  MenuGroup(key: "MenuGroup"),
  MenuName(key: "MenuName"),
  MessengerId(key: "MessengerId"),
  Method(key: "Method"),
  ModbusObjectType(key: "ModbusObjectType"),
  ModelCode(key: "ModelCode"),
  ModelId(key: "ModelId"),
  ModelName(key: "ModelName"),
  ModelNumber(key: "ModelNumber"),
  MonitoringType(key: "MonitoringType"),
  MoldCode(key: "MoldCode"),
  MoldName(key: "MoldName"),
  MoldNumber(key: "MoldNumber"),
  MoldSpec(key: "MoldSpec"),
  MoldId(key: "MoldId"),

  //endregion

  ///region N
  Name(key: "Name"),
  NetAmount(key: "NetAmount"),
  NextInspectionNumber(key: "NextInspectionNumber"),
  NextInspectionResultNumber(key: "NextInspectionResultNumber"),
  NextMeasurementResultNumber(key: "NextMeasurementResultNumber"),
  Node(key: "Node"),
  NonClosingQuantity(key: "NonClosingQuantity"),
  NonPutAwayQuantity(key: "NonPutAwayQuantity"),
  NonReceiptQuantity(key: 'NonReceiptQuantity'),
  NonReturnQuantity(key: 'NonReturnQuantity'),
  Number(key: "Number"),
  NumTransformation(key: "NumTransformation"),

  //endregion

  ///region O
  Occurred(key: "Occurred"),
  OffDutyTime(key: "OffDutyTime"),
  OpcSecurityAlgorithm(key: "OpcSecurityAlgorithm"),
  OpcSecurityMode(key: "OpcSecurityMode"),
  OperatingOrderLines(key: "OperatingOrderLines"),
  OrderActualEndTime(key: "OrderActualEndTime"),
  OrderActualStartTime(key: "OrderActualStartTime"),
  OrderCycleTime(key: "OrderCycleTime"),
  OrderCycleTimeSeconds(key: "OrderCycleTimeSeconds"),
  OrderDate(key: 'OrderDate'),
  OrderId(key: 'OrderId'),
  OrderIndex(key: "OrderIndex"),
  OrderLabels(key: "OrderLabels"),
  OrderLineId(key: 'OrderLineId'),
  OrderLines(key: 'OrderLines'),
  OrderList(key: 'OrderList'),
  OrderMaterials(key: 'OrderMaterials'),
  OrderMolds(key: 'OrderMolds'),
  OrderNumber(key: 'OrderNumber'),
  OrderQuantity(key: 'OrderQuantity'),
  OrderRealWorkTime(key: 'OrderRealWorkTime'),
  OrderRealWorkTimeMinutes(key: 'OrderRealWorkTimeMinutes'),
  OrderStatus(key: 'OrderStatus'),
  OrderType(key: 'OrderType'),
  OtherLossQuantity(key: 'OtherLossQuantity'),

  //endregion

  ///region P
  PasDataType(key: "PasDataType"),
  PassCount(key: "PassCount"),
  Password(key: "Password"),
  Path(key: "Path"),
  PauseTime(key: 'PauseTime'),
  Permissions(key: "Permissions"),
  PhoneNumber(key: "PhoneNumber"),
  PV(key: "PV"),
  PickingId(key: 'PickingId'),
  PickingLineId(key: 'PickingLineId'),
  PickingNumber(key: 'PickingNumber'),
  PickingQty(key: 'PickingQty'),
  PickingQuantity(key: 'PickingQuantity'),
  PickingQuantityLeft(key: 'PickingQuantityLeft'),
  PickingTime(key: 'PickingTime'),
  PickingType(key: 'PickingType'),
  Pitch(key: 'Pitch'),
  PlanBreakTime(key: 'PlanBreakTime'),
  PlanDate(key: 'PlanDate'),
  PlanEndTime(key: 'PlanEndTime'),
  PlanOperatingTime(key: 'PlanOperatingTime'),
  PlanQuantity(key: 'PlanQuantity'),
  PlanStartTime(key: 'PlanStartTime'),
  PlanType(key: 'PlanType'),
  Port(key: "Port"),
  Position(key: "Position"),
  PostLineId(key: "PostLineId"),
  PostLineItems(key: 'PostLineItems'),
  PressMolds(key: 'PressMolds'),
  PreviousLotRecords(key: 'PreviousLotRecords'),
  PreviousProcess(key: 'PreviousProcess'),
  PriceRecordId(key: "PriceRecordId"),
  ProcessCategoryId(key: 'ProcessCategoryId'),
  ProcessCategoryName(key: 'ProcessCategoryName'),
  ProcessName(key: 'ProcessName'),
  ProcessOrder(key: 'ProcessOrder'),
  ProcessType(key: 'ProcessType'),
  ProductionPeriod(key: "ProductionPeriod"),
  ProductionPeriodQuantity(key: "ProductionPeriodQuantity"),
  ProtocolType(key: "ProtocolType"),
  ProductionBases(key: 'ProductionBases'),
  ProductionQuantity(key: 'ProductionQuantity'),
  ProductionType(key: 'ProductionType'),
  PurchasePeriod(key: "PurchasePeriod"),
  PutAwayCompleted(key: "PutAwayCompleted"),
  PutAwayQuantity(key: 'PutAwayQuantity'),
  PutAwayQty(key: 'PutAwayQty'),

  //endregion

  ///region Q

  QuantityType(key: 'QuantityType'),

  //endregion

  ///region R
  RawData(key: "RawData"),
  RealUpTime(key: "RealUpTime"),
  RealWorkTime(key: "RealWorkTime"),
  Reason(key: "Reason"),
  ReasonCode(key: 'ReasonCode'),
  ReasonId(key: 'ReasonId'),
  ReasonName(key: 'ReasonName'),
  ReceiptDate1(key: 'ReceiptDate1'),
  ReceiptDate2(key: 'ReceiptDate2'),
  ReceiptDueDate(key: 'ReceiptDueDate'),
  ReceiptLineId(key: 'ReceiptLineId'),
  ReceiptNumber(key: 'ReceiptNumber'),
  ReceiptQuantity(key: 'ReceiptQuantity'),
  ReceiptId(key: 'ReceiptId'),
  ReceiptTime(key: 'ReceiptTime'),
  ReceiptType(key: 'ReceiptType'),
  ReceiverCode(key: 'ReceiverCode'),
  ReceiverId(key: 'ReceiverId'),
  ReceiverName(key: 'ReceiverName'),
  RecordId(key: 'RecordId'),
  ReferenceFieldName(key: 'ReferenceFieldName'),
  ReferenceType(key: "ReferenceType"),
  RequisitionLineId(key: 'RequisitionLineId'),
  RequisitionQuantity(key: 'RequisitionQuantity'),
  RequisitionQuantityLeft(key: 'RequisitionQuantityLeft'),
  ResponseMethod(key: "ResponseMethod"),
  ResponseTime(key: "ResponseTime"),
  ResponseType(key: "ResponseType"),
  ResultCount(key: "ResultCount"),
  ResultNumber(key: "ResultNumber"),
  ReturnCompleted(key: "ReturnCompleted"),
  ReturnQuantity(key: "ReturnQuantity"),
  ReturnQuantityLeft(key: "ReturnQuantityLeft"),
  ReworkTime(key: "ReworkTime"),
  RunningStatus(key: "RunningStatus"),

  //endregion

  ///region S
  SalesOrderLineId(key: 'SalesOrderLineId'),
  SalesPeriod(key: "SalesPeriod"),
  SaveDataType(key: "SaveDataType"),
  SavingMethod(key: "SavingMethod"),
  ScheduleId(key: 'ScheduleId'),
  SchedulingNumber(key: 'SchedulingNumber'),
  SelectionQuantity(key: 'SelectionQuantity'),
  SellerCode(key: 'SellerCode'),
  SellerCurrency(key: 'SellerCurrency'),
  SellerId(key: 'SellerId'),
  SellerName(key: 'SellerName'),
  SenderCode(key: 'SenderCode'),
  SenderId(key: 'SenderId'),
  SenderName(key: 'SenderName'),
  ServerId(key: "ServerId"),
  ServerPassword(key: "ServerPassword"),
  Severity(key: "Severity"),
  ShiftCode(key: "ShiftCode"),
  ShiftId(key: "ShiftId"),
  ShiftName(key: "ShiftName"),
  Signed(key: "Signed"),
  SizeInfo(key: "SizeInfo"),
  SizeType(key: "SizeType"),
  Spec(key: "Spec"),
  SpecType(key: "SpecType"),
  Speed(key: "Speed"),
  StartTime(key: "StartTime"),
  State(key: "State"),
  Status(key: "Status"),
  Street(key: "Street"),
  SubcontractOrderLineId(key: 'SubcontractOrderLineId'),
  SubCategoryId(key: 'SubCategoryId'),
  SubCategoryName(key: 'SubCategoryName'),
  SuperCategory(key: 'SuperCategory'),
  SV(key: "SV"),

  //endregion

  ///region T

  ///target
  TargetCompletionRate(key: 'TargetCompletionRate'),
  TargetCompletionRateAverage(key: 'TargetCompletionRateAverage'),
  TargetManagers(key: "TargetManagers"),
  TargetQuantity(key: "TargetQuantity"),
  TargetUnitsPerMinute(key: "TargetUnitsPerMinute"),
  TargetUnitsNow(key: "TargetUnitsNow"),
  TaxBillEmail(key: "TaxBillEmail"),
  TaxBillName(key: "TaxBillName"),
  TextureCode(key: "TextureCode"),
  TextureId(key: "TextureId"),
  TextureName(key: "TextureName"),
  Token(key: "Token"),
  TotalDefectQuantity(key: "TotalDefectQuantity"),
  TotalGrossAmount(key: "TotalGrossAmount"),
  TotalInspectionCount(key: 'TotalInspectionCount'),
  TotalLossQuantity(key: 'TotalLossQuantity'),
  TotalMaterialInsertQty(key: 'TotalMaterialInsertQty'),
  TotalMaterialLossQty(key: 'TotalMaterialLossQty'),
  TotalMaterialUseQty(key: 'TotalMaterialUseQty'),
  TotalNetAmount(key: "TotalNetAmount"),
  TotalTime(key: "TotalTime"),
  TotalVatAmount(key: "TotalVatAmount"),
  Type(key: "Type"),

  //endregion

  ///region U
  UB(key: "UB"),
  Unit(key: "Unit"),
  UnitEffectiveQuantity(key: "UnitEffectiveQuantity"),
  UnitLossQuantity(key: "UnitLossQuantity"),
  UnitLossRate(key: "UnitLossRate"),
  UnitOperatingTime(key: "UnitOperatingTime"),
  UnitPrice(key: "UnitPrice"),
  UnitRequiredQuantity(key: "UnitRequiredQuantity"),
  UnitsPerHour(key: "UnitsPerHour"),
  UnitsPerMinute(key: "UnitsPerMinute"),
  UnitTransferTime(key: "UnitTransferTime"),
  UpTime(key: "UpTime"),

  /// use
  UseAssembly(key: "UseAssembly"),
  UseAssemblyProcess(key: "UseAssemblyProcess"),
  UseBlending(key: "UseBlending"),
  UseBlendingProcess(key: "UseBlendingProcess"),
  UseClosing(key: "UseClosing"),
  UseCustom(key: "UseCustom"),
  UseCustomProcess(key: "UseCustomProcess"),
  UseCutting(key: "UseCutting"),
  UseCuttingProcess(key: "UseCuttingProcess"),
  UseHandwork(key: "UseHandwork"),
  UseHandworkProcess(key: "UseHandworkProcess"),
  UseInspection(key: "UseInspection"),
  UseInspectionProcess(key: "UseInspectionProcess"),
  UseLogin(key: "UseLogin"),
  UseMolding(key: "UseMolding"),
  UseMoldingProcess(key: "UseMoldingProcess"),
  UsePainting(key: "UsePainting"),
  UsePaintingProcess(key: "UsePaintingProcess"),
  UsePress(key: "UsePress"),
  UsePressProcess(key: "UsePressProcess"),
  UseProductionSupply(key: "UseProductionSupply"),
  UsePurchaseSupply(key: "UsePurchaseSupply"),
  UserDataType(key: "UserDataType"),
  UseSubcontractSupply(key: "UseSubcontractSupply"),
  UsedQuantity(key: 'UsedQuantity'),

  //endregion

  ///region V

  Value(key: "Value"),
  VatIncludedValue(key: "VatIncludedValue"),
  VatAmount(key: "VatAmount"),
  VatIncluded(key: "VatIncluded"),
  VatRate(key: "VatRate"),

  //endregion

  ///region W
  WarehouseCode(key: 'WarehouseCode'),
  WarehouseId(key: 'WarehouseId'),
  WarehouseName(key: 'WarehouseName'),
  WordOrder(key: 'WordOrder'),
  WorkerCode(key: 'WorkerCode'),
  WorkFlowId(key: 'WorkFlowId'),
  WorkerCount(key: 'WorkerCount'),
  WorkerName(key: 'WorkerName'),
  WorkerId(key: 'WorkerId'),
  Workers(key: 'Workers'),
  WorkerStatus(key: 'WorkerStatus'),

  //endregion

  /// region X


  //endregion

  /// region Y

  //endregion

  /// region Z

  ZipCode(key: "ZipCode"),

  //endregion

  /// region 오타(수정 x)
  AcutalWorkTime(key: 'AcutalWorkTime'),
  CycleTimel(key: 'CycleTimel'),
  DieHieght(key: 'DieHieght'),
  LotNubmer(key: 'LotNubmer'),
  MiniteTargetQuantity(key: "MiniteTargetQuantity"),
  RepresentiveDirector(key: "RepresentiveDirector"),
  ReponseCodeId(key: "ReponseCodeId"),

  //endregion

  ;

  const ApiJsonKey({required this.key});

  final String key;
}
